# Generated by Django 5.0.6 on 2024-05-26 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quanta.category'),
        ),
        migrations.AlterField(
            model_name='text',
            name='entropy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='text',
            name='shannon_value',
            field=models.FloatField(default=0.0),
        ),
    ]
