# Generated by Django 5.0.6 on 2024-06-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanta', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
        migrations.AlterField(
            model_name='text',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='quanta.category'),
        ),
    ]
